### ISSUE TITLE
updated the keria instance to include debugging output in the logs

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot#102]

**Comment by 2byrds** [comment]
@ronakseth96 based on ur changes i think we can close this issue if you add those changes to the reg-pilot run of KERIA?

**Comment by ronakseth96** [comment]
@2byrds For now, I could recreate the logs on docker with the log level set to error when starting the instance, similar to what we observed on the remote KERIA instance. I've removed the log level parameter from the remote instances for now. Once everything checks out with the reg-pilot tests, I'll sync it to align docker and remote instances.

**Comment by 2byrds** [comment]
@ronakseth96 can we close this?

**Comment by ronakseth96** [comment]
@2byrds Based on our discussion, I adjusted the log level from `Error` to `Debug` during the deployment. Everything looks good now, so I’ll go ahead and close this.
