### ISSUE TITLE
Modify multisig test to properly create delegate (QVI) AID 

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot#73]
It is written for the old flow of delegation. Instead the delegate (QVI) AID should be able to be created (and witnessed) before the delegator (GEDA) approves the delegation.
Avoid using the AID operation to retrieve the AID prefix. Instead retrieve the AID from the QVI client.

**Comment by 2byrds** [comment]
@aydarng can we close this?

**Comment by aydarng** [comment]
> @aydarng can we close this?

Yes
