### ISSUE TITLE
Add delegation configuration and introduce GLEIF internal/external delegation relationship

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot#92]
Error reported by @lenkan and our test data should simulate the internal/external.
Essentially there are two levels of delegation, the ECR login cesr was not providing the delegator cesr.
There should be delegation between GLEIF internal->GLEIF external, and GLEIF->external -> QVI.

**Comment by 2byrds** [comment]
related to https://github.com/GLEIF-IT/reg-pilot/issues/73

**Comment by 2byrds** [comment]
@aydarng can we close this?

**Comment by aydarng** [comment]
> @aydarng can we close this?

Can be closed @2byrds
